
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace adminpanel.Models
{

using System;
    using System.Collections.Generic;
    
public partial class attByClient
{

    public int empid { get; set; }

    public string MarkDate { get; set; }

    public string MarkTime { get; set; }

    public string Coordinates { get; set; }

    public Nullable<int> CompanyId { get; set; }

    public string EmpName { get; set; }

}

}
