//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminpanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class attRepTemp
    {
        public int attendanceid { get; set; }
        public int empid { get; set; }
        public string MarkDate { get; set; }
        public string MarkTime { get; set; }
        public string Coordinates { get; set; }
        public Nullable<int> MarkCount { get; set; }
    }
}
