//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminpanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class claimJSON
    {
        public int id { get; set; }
        public int EmpId { get; set; }
        public string claimNo { get; set; }
        public System.DateTime claimDate { get; set; }
        public string claimPurpose { get; set; }
        public string claimText { get; set; }
        public decimal totalAmount { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
