//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminpanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class claimHistory
    {
        public int Id { get; set; }
        public int claimId { get; set; }
        public int statusId { get; set; }
        public string remarks { get; set; }
        public System.DateTime statusTime { get; set; }
        public int actionBy { get; set; }
    
        public virtual claimJSON claimJSON { get; set; }
        public virtual ClaimStatu ClaimStatu { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
