
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace adminpanel.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ClaimStatu
{

    public ClaimStatu()
    {

        this.ClaimStatusHistories = new HashSet<ClaimStatusHistory>();

        this.claimHistories = new HashSet<claimHistory>();

        this.claimJSONs = new HashSet<claimJSON>();

    }


    public int Id { get; set; }

    public string Status { get; set; }



    public virtual ICollection<ClaimStatusHistory> ClaimStatusHistories { get; set; }

    public virtual ICollection<claimHistory> claimHistories { get; set; }

    public virtual ICollection<claimJSON> claimJSONs { get; set; }

}

}
