//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminpanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimLine
    {
        public int Id { get; set; }
        public int ClaimId { get; set; }
        public int ClaimLineId { get; set; }
        public int ClaimType { get; set; }
        public string Purpose { get; set; }
        public byte LocOut { get; set; }
        public string HotelName { get; set; }
        public System.DateTime ExpenseDate { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> AccNoOfNights { get; set; }
        public string TravelFromPlace { get; set; }
        public string TravelToPlace { get; set; }
        public string TravelMode { get; set; }
        public Nullable<double> Distance { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string OtherClaimTypeDesc { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<byte> BillType { get; set; }
        public int LineStatus { get; set; }
        public string EmpRemarks { get; set; }
        public string ManagerRemarks { get; set; }
        public string OrgRemarks { get; set; }
    
        public virtual ClaimHead ClaimHead { get; set; }
        public virtual ClaimStatu ClaimStatu { get; set; }
    }
}
