//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminpanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.GroupTypes = new HashSet<GroupType>();
        }
    
        public int ClientId { get; set; }
        public string ClientName { get; set; }
        public Nullable<int> OrgId { get; set; }
        public string ClientLogoURL { get; set; }
    
        public virtual ICollection<GroupType> GroupTypes { get; set; }
    }
}
