
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace adminpanel.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Degree
{

    public Degree()
    {

        this.EmpQualifications = new HashSet<EmpQualification>();

    }


    public int Id { get; set; }

    public string DegreeName { get; set; }

    public int Qualification { get; set; }



    public virtual Qualification Qualification1 { get; set; }

    public virtual ICollection<EmpQualification> EmpQualifications { get; set; }

}

}
