
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace adminpanel.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EmergencyContact
{

    public int Id { get; set; }

    public int EmpId { get; set; }

    public string ContactName { get; set; }

    public int Relation { get; set; }

    public Nullable<System.DateTime> modifieddate { get; set; }

    public Nullable<System.DateTime> createdate { get; set; }

    public int entityaddressid { get; set; }



    public virtual Employee Employee { get; set; }

    public virtual EntityAddress EntityAddress { get; set; }

    public virtual Relation Relation1 { get; set; }

}

}
