
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace adminpanel.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EmpContactDetail
{

    public int Id { get; set; }

    public int EmpId { get; set; }

    public int contactLineId { get; set; }

    public int contactTypeId { get; set; }

    public string contactLable { get; set; }

    public string contactData { get; set; }



    public virtual contactType contactType { get; set; }

    public virtual Employee Employee { get; set; }

}

}
