
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace adminpanel.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EmpDoc
{

    public int Id { get; set; }

    public int EmpId { get; set; }

    public int DocTypeId { get; set; }

    public string DocRemarks { get; set; }

    public string DocReference { get; set; }



    public virtual DocType DocType { get; set; }

    public virtual Employee Employee { get; set; }

}

}
