
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace adminpanel.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EmpIdentity
{

    public int EmpID { get; set; }

    public string DL { get; set; }

    public string Adhaar { get; set; }

    public string Voter { get; set; }

    public string Passport { get; set; }

    public string Pan { get; set; }

    public Nullable<System.DateTime> modified { get; set; }

    public Nullable<System.DateTime> created { get; set; }



    public virtual Employee Employee { get; set; }

}

}
