
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace adminpanel.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Employee
{

    public Employee()
    {

        this.Attendances = new HashSet<Attendance>();

        this.Candidates = new HashSet<Candidate>();

        this.Candidates1 = new HashSet<Candidate>();

        this.claimHistories = new HashSet<claimHistory>();

        this.claimJSONs = new HashSet<claimJSON>();

        this.ClaimRevisions = new HashSet<ClaimRevision>();

        this.EmergencyContacts = new HashSet<EmergencyContact>();

        this.EmpContactDetails = new HashSet<EmpContactDetail>();

        this.EmpDocs = new HashSet<EmpDoc>();

        this.EmpJDs = new HashSet<EmpJD>();

        this.EmpJDs1 = new HashSet<EmpJD>();

        this.EmpJDs2 = new HashSet<EmpJD>();

        this.EmpPastEmps = new HashSet<EmpPastEmp>();

        this.EmpQualifications = new HashSet<EmpQualification>();

        this.GroupEmployees = new HashSet<GroupEmployee>();

        this.GroupIncharges = new HashSet<GroupIncharge>();

        this.GroupTypeIncharges = new HashSet<GroupTypeIncharge>();

        this.JobDescriptions = new HashSet<JobDescription>();

        this.JobDescriptions1 = new HashSet<JobDescription>();

    }


    public int EmpId { get; set; }

    public string EmpNum { get; set; }

    public string EmpName { get; set; }

    public string ProfilePic { get; set; }

    public int EmpStatus { get; set; }

    public string Email { get; set; }

    public Nullable<long> PrimaryMobile { get; set; }

    public string Designation { get; set; }

    public string AuthUserId { get; set; }

    public Nullable<int> CompanyId { get; set; }



    public virtual ICollection<Attendance> Attendances { get; set; }

    public virtual ICollection<Candidate> Candidates { get; set; }

    public virtual ICollection<Candidate> Candidates1 { get; set; }

    public virtual ICollection<claimHistory> claimHistories { get; set; }

    public virtual ICollection<claimJSON> claimJSONs { get; set; }

    public virtual ICollection<ClaimRevision> ClaimRevisions { get; set; }

    public virtual ICollection<EmergencyContact> EmergencyContacts { get; set; }

    public virtual ICollection<EmpContactDetail> EmpContactDetails { get; set; }

    public virtual ICollection<EmpDoc> EmpDocs { get; set; }

    public virtual EmpFinDetail EmpFinDetail { get; set; }

    public virtual EmpIdentity EmpIdentity { get; set; }

    public virtual ICollection<EmpJD> EmpJDs { get; set; }

    public virtual ICollection<EmpJD> EmpJDs1 { get; set; }

    public virtual ICollection<EmpJD> EmpJDs2 { get; set; }

    public virtual EmpStatu EmpStatu { get; set; }

    public virtual ICollection<EmpPastEmp> EmpPastEmps { get; set; }

    public virtual ICollection<EmpQualification> EmpQualifications { get; set; }

    public virtual ICollection<GroupEmployee> GroupEmployees { get; set; }

    public virtual ICollection<GroupIncharge> GroupIncharges { get; set; }

    public virtual ICollection<GroupTypeIncharge> GroupTypeIncharges { get; set; }

    public virtual ICollection<JobDescription> JobDescriptions { get; set; }

    public virtual ICollection<JobDescription> JobDescriptions1 { get; set; }

    public virtual Login Login { get; set; }

}

}
