//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminpanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Attendances = new HashSet<Attendance>();
            this.GroupEmployees = new HashSet<GroupEmployee>();
            this.GroupIncharges = new HashSet<GroupIncharge>();
            this.claimJSONs = new HashSet<claimJSON>();
            this.claimHistories = new HashSet<claimHistory>();
            this.ClaimRevisions = new HashSet<ClaimRevision>();
            this.EmpContactDetails = new HashSet<EmpContactDetail>();
            this.EmergencyContacts = new HashSet<EmergencyContact>();
            this.EmpQualifications = new HashSet<EmpQualification>();
            this.EmpPastEmps = new HashSet<EmpPastEmp>();
        }
    
        public int EmpId { get; set; }
        public string EmpNum { get; set; }
        public string EmpName { get; set; }
        public string ProfilePic { get; set; }
        public int EmpStatus { get; set; }
        public string Email { get; set; }
        public Nullable<long> PrimaryMobile { get; set; }
        public string Designation { get; set; }
        public string AuthUserId { get; set; }
        public Nullable<int> CompanyId { get; set; }
    
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual EmpStatu EmpStatu { get; set; }
        public virtual Login Login { get; set; }
        public virtual ICollection<GroupEmployee> GroupEmployees { get; set; }
        public virtual ICollection<GroupIncharge> GroupIncharges { get; set; }
        public virtual ICollection<claimJSON> claimJSONs { get; set; }
        public virtual ICollection<claimHistory> claimHistories { get; set; }
        public virtual ICollection<ClaimRevision> ClaimRevisions { get; set; }
        public virtual EmpFinDetail EmpFinDetail { get; set; }
        public virtual EmpIdentity EmpIdentity { get; set; }
        public virtual ICollection<EmpContactDetail> EmpContactDetails { get; set; }
        public virtual ICollection<EmergencyContact> EmergencyContacts { get; set; }
        public virtual ICollection<EmpQualification> EmpQualifications { get; set; }
        public virtual ICollection<EmpPastEmp> EmpPastEmps { get; set; }
    }
}
