//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminpanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpPastEmp
    {
        public int Id { get; set; }
        public int EmpId { get; set; }
        public string Company { get; set; }
        public string Designation { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
