
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace adminpanel.Models
{

using System;
    
public partial class getAttendanceByClientsDays_Result1
{

    public int EmpId { get; set; }

    public string Emp_Name { get; set; }

    public Nullable<System.DateTime> MarkDate { get; set; }

    public Nullable<System.TimeSpan> MarkingTime { get; set; }

    public string Coordinates { get; set; }

    public Nullable<int> MarkCount { get; set; }

}

}
