
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace adminpanel.Models
{

using System;
    using System.Collections.Generic;
    
public partial class GroupType
{

    public GroupType()
    {

        this.Groups = new HashSet<Group>();

        this.GroupTypeIncharges = new HashSet<GroupTypeIncharge>();

    }


    public int Id { get; set; }

    public string GroupType1 { get; set; }

    public int ClientId { get; set; }



    public virtual Client Client { get; set; }

    public virtual ICollection<Group> Groups { get; set; }

    public virtual ICollection<GroupTypeIncharge> GroupTypeIncharges { get; set; }

}

}
