
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace adminpanel.Models
{

using System;
    using System.Collections.Generic;
    
public partial class JobBenefit
{

    public int Id { get; set; }

    public int JobId { get; set; }

    public int BenefitId { get; set; }

    public string BenefitDesc { get; set; }



    public virtual Benefit Benefit { get; set; }

    public virtual JobDescription JobDescription { get; set; }

}

}
