
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace adminpanel.Models
{

using System;
    using System.Collections.Generic;
    
public partial class LogType
{

    public LogType()
    {

        this.LogTables = new HashSet<LogTable>();

    }


    public int Id { get; set; }

    public string LogTypeName { get; set; }



    public virtual ICollection<LogTable> LogTables { get; set; }

}

}
