
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace adminpanel.Models
{

using System;
    using System.Collections.Generic;
    
public partial class RecruitmentStage
{

    public RecruitmentStage()
    {

        this.CandidateRecruitments = new HashSet<CandidateRecruitment>();

    }


    public int Id { get; set; }

    public string StageName { get; set; }



    public virtual ICollection<CandidateRecruitment> CandidateRecruitments { get; set; }

}

}
