
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace adminpanel.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Relation
{

    public Relation()
    {

        this.EmergencyContacts = new HashSet<EmergencyContact>();

    }


    public int id { get; set; }

    public string RelationName { get; set; }



    public virtual ICollection<EmergencyContact> EmergencyContacts { get; set; }

}

}
