
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace adminpanel.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Skill
{

    public Skill()
    {

        this.CandidateSkills = new HashSet<CandidateSkill>();

        this.Certifications = new HashSet<Certification>();

        this.JobSkills = new HashSet<JobSkill>();

    }


    public int Id { get; set; }

    public string SkillName { get; set; }

    public int SkillGroupId { get; set; }



    public virtual ICollection<CandidateSkill> CandidateSkills { get; set; }

    public virtual ICollection<Certification> Certifications { get; set; }

    public virtual ICollection<JobSkill> JobSkills { get; set; }

    public virtual SkillGroup SkillGroup { get; set; }

}

}
