
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace adminpanel.Models
{

using System;
    using System.Collections.Generic;
    
public partial class vProfileDetail
{

    public int empid { get; set; }

    public Nullable<int> Basic_Detail { get; set; }

    public Nullable<int> Contact_Detail { get; set; }

    public Nullable<int> Addresses { get; set; }

    public Nullable<int> Bank { get; set; }

    public Nullable<int> Identity { get; set; }

    public Nullable<int> PastEmp { get; set; }

    public Nullable<int> Qualification { get; set; }

    public Nullable<int> Emergency { get; set; }

}

}
