
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace adminpanel.Models
{

using System;
    using System.Collections.Generic;
    
public partial class vSubmittedClaim
{

    public int id { get; set; }

    public int empid { get; set; }

    public string claimNo { get; set; }

    public System.DateTime claimDate { get; set; }

    public string claimPurpose { get; set; }

    public decimal totalAmount { get; set; }

    public int claimstatus { get; set; }

    public string ClaimStatusName { get; set; }

    public string claimText { get; set; }

    public Nullable<System.DateTime> claimperiodfrom { get; set; }

    public Nullable<System.DateTime> claimperiodto { get; set; }

}

}
